version: '3'
services:
  shiny:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "3838:3838"
    command: R -e "shiny::runApp('/code/shiny-explore-dataset', host='0.0.0.0', port=3838, launch.browser = FALSE)"
  bash:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    stdin_open: true # docker run -i
    tty: true        # docker run -t
